name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check README
        run: test -f README.md

      - name: Finish
        run: echo "CI passed"
